/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package uk.gov.justice.digital.legaladviser.test;

import org.junit.Test;
import uk.gov.justice.digital.legaladviser.App;

import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static uk.gov.justice.digital.legaladviser.resources.ConfigSettings.homePage;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = App.class)
@AutoConfigureMockMvc
public class AppTest {

    @Autowired
    private MockMvc mvc;

    @Test
    public void home_page_should_return_httpok() throws Exception {
        mvc.perform(get("/"))
                .andExpect(status().isOk())
                .andExpect(content().string(homePage));
    }


    @Test
    public void find_by_id_return_httpok() throws Exception {
        mvc.perform(get("/legaladviser/1"))
                .andExpect(status().isOk());
    }

    @Test
    public void find_all_return_httpok() throws Exception {
        mvc.perform(get("/legaladvisers"))
                .andExpect(status().isOk());
    }

}