/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.justice.digital.legaladviser;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import uk.gov.justice.digital.legaladviser.resources.ConfigSettings;

import java.util.Arrays;

/* Usage  gradlew bootRun --args='--db=legal-providers.csv' */
@SpringBootApplication
public class App implements ApplicationRunner {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String... args) {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(ApplicationArguments args) {

        logger.info("Application started with command-line arguments: {}", Arrays.toString(args.getSourceArgs()));
        logger.info("NonOptionArgs: {}", args.getNonOptionArgs());
        logger.info("OptionNames: {}", args.getOptionNames());

        for (String name : args.getOptionNames()) {
            logger.info("arg-" + name + "=" + args.getOptionValues(name));
        }
        boolean containsOption = args.containsOption("db");
        String db="";
        if(containsOption) {
            logger.info("Contains file name: " + containsOption);
             db = args.getOptionValues("db").get(0);
            ConfigSettings.setDbFile(db);
        }

        logger.info("db=" + db + "  , ConfigSettings.dbFile =" + ConfigSettings.getDbFile());
    }
}